### ISSUE TITLE
animated gifs - preserve animation

### ISSUE THREAD

**Issue by benzkji** [SmileyChris/easy-thumbnails#184]
I wonder if this could be somehow achieved?

Tried

``` python
    THUMBNAIL_PRESERVE_EXTENSIONS = ('gif',)
```

what preserves the ".gif" extension, but not the animation.

Thx for any pointers / help.
Ben

**Comment by philipplaeubli** [comment]
Is there still no solution for this? @melbic how did you solve the problem?

**Comment by melbic** [comment]
No, I don't think so. :/

**Comment by wfehr** [comment]
Another year later, same question: Are there any solutions on this?
