### ISSUE TITLE
many requests to cdn when using django-cumulus

### ISSUE THREAD

**Issue by jslootbeek** [SmileyChris/easy-thumbnails#214]
I'm using easy-thumbnail with django-cumulus to store my thumbnails and source files on a CDN. When I have a list of {% thumbnail ... %} templatetags, I notice that for each templatetag, easy-thumbnail will create a new CloudStorageFile class, and a new connection to my CDN. This is getting rather expensive (time-wise) and is causing pages to load slowly as each request to the CDN takes on average 500ms. While I wil work with RackSpace to address that issue (IMO it shouldn't be that long). I was wondering if there is anything we can do from an easy-thumbnail perspective to reduce the amount of HTTP queries to the CDN. I'm not sure if this is a easy-thumbnail issue, or a django-cumulus issue, or a django-cloudfiles issue, but I figured I'd start at the top of the chain.
Any help or pointers would be appreciated.

**Comment by erichonkanen** [comment]
Has anyone run into this problem more recently? We are running into it using django-cumulus with easy-thumbnails when async generating thumbnails for files pushed to cloudfiles...
