### ISSUE TITLE
Easy thumbnails with remote storages like S3

### ISSUE THREAD

**Issue by aykut** [SmileyChris/easy-thumbnails#283]
Hi,

I'm using amazon S3 as remote storage and easy-thumbnails for creating thumbnails. However, easy-thumbnails queries to db for each thumbnail and it is so slow to check existency and modified time of image for every thumbnail. Thus this makes using remote storage and easy-thumbnails together so slow. Actually, I think this is already a known issue.

I've forked your project and made some fixes for these issues. If you want to check, https://github.com/aykutozat/easy-thumbnails.

Basically, I changed your `get_modtime` methods for remote storages, it solved the query problem. However, checking the path and modified time of the image was still consuming much time. So I cache the modified time of thumbnails and source images.

Apart from all of these, there is still a problem which is saving the thumbnails into remote storage which consumes much time as well. I'm thinking of using celery for this issue. I will use user's local storage(media folder) for "temporary thumbnails" at first creation(or even maybe base64 format of the image can be used not sure) and pass the "real creation" to celery and after it creates the thumbnail, it will also delete the created "temporary thumbnail" from user's local storage.

I didn't want to open a pull request because I'm using cache which you may not like and I also want to add celery thing. However I wanted to take your opinions on my suggestions.

Thanks.

**Comment by bemall** [comment]
Hellos, I am wondering if this was every resolved and or if updates attended to this ? Thanks

**Comment by susheelbanyal** [comment]
Yes is works like this way in settings. You have to set THUMBNAIL_DEFAULT_STORAGE to storages.backends.s3boto.S3BotoStorage like below:
THUMBNAIL_DEFAULT_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

**Comment by caliph007** [comment]
When I deploy the storages-S3 backend I increase the number of thumbnail DB queries significantly.
Its several DB queries per thumbnail.

If I use the filesystem to store the media files, there is no (!) DB query when rendering a page that has (already processed) thumbnails.

 I have a 100 thumbnail page and over 700 DB calls: more than 600 because of easy thumbnails.

Why is that?

I assume its faster to query the DB that check on S3 for the image, but:
Isn't 1 DB query per image sufficient?

**Comment by kayluhb** [comment]
@caliph007 did you ever figure out a solution to this?

**Comment by VdeJong** [comment]
I'm having the same problem as @caliph007. Anyone got a solution to this?

**Comment by kayluhb** [comment]
I don't have a solution yet, but I'm exploring using https://github.com/s3fs-fuse/s3fs-fuse to make the s3 files available on the server so it goes back to using the filesystem for the image dimension lookup. Not ideal, but it seems promising so far.
