### ISSUE TITLE
thumbnail_url tag retrieve empty string

### ISSUE THREAD

**Issue by chogarcia** [SmileyChris/easy-thumbnails#305]
I did exactly the same as the docs: installed apps, create thumbnails aliases and then load the template tag. 

```
settings.py
INSTALLED_APPS = (
    ...
    'easy_thumbnails',
    ...
)

THUMBNAIL_ALIASES = {
    '': {
        'avatar': {'size': (50, 50), 'crop': True},
    },
}

template.html
{% load thumbnail %}
<img src="{{ item.main_image|thumbnail_url:'avatar' }}" alt="" />
```

I´ve installed Pillow==2.3.1 and easy-thumbnails==1.5.

What am I doing wrong?

**Comment by jpic** [comment]
Helped me find out my wrong MEDIA_ROOT in certain environments.
