### ISSUE TITLE
Sometimes Image._getexif flakes out on seemingly legit images

### ISSUE THREAD

**Issue by dpnova** [SmileyChris/easy-thumbnails#335]
Was great meeting you at pycon Chris :)

On to business..

I'm opening this issue more a way to solicit input from anyone who cares, once we agree on a solution I can implement!

There could also be a bug in PIL here, just need to make sure we attack at the right level...

```
>>> d = urllib.urlopen("https://scrunchmedia.s3.amazonaws.com/story_images/e3f979e1c6cf4a744e395c8618648856.jpe").read()
>>> i = StringIO.StringIO(d)
>>> img = Image.open(i)
>>> img._getexif()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/.virtualenvs/crawler/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 362, in _getexif
    return _getexif(self)
  File "/home/vagrant/.virtualenvs/crawler/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 385, in _getexif
    info = TiffImagePlugin.ImageFileDirectory(head)
  File "/home/vagrant/.virtualenvs/crawler/local/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 270, in __init__
    raise SyntaxError("not a TIFF IFD")
SyntaxError: not a TIFF IFD
>>> 
```

I could "fix" this by handling the exception, but I'm just wondering if this particular exception has not been handled here for a reason.

**Comment by sergei-maertens** [comment]
Any option to add TypeError to that list? The image https://modelbrouwers.nl/media/albums/44/3370/DSC_4458.jpg is causing trouble for me, see also https://github.com/python-pillow/Pillow/issues/1359

**Comment by SmileyChris** [comment]
Version 2.2 onwards covers all Exceptions, see a67f18e3d1dfd09cd73f77d1ac8aa9c29a00711f

**Comment by sergei-maertens** [comment]
I must have missed that, time to check which version I have installed.
