### ISSUE TITLE
Incorrect transparent PNG upload behaviour using S3

### ISSUE THREAD

**Issue by askaliuk** [SmileyChris/easy-thumbnails#337]
I've tried to use `easy_thumbnails` with S3 Boto.
- trying to upload `user.png` with a transparency layer using 2 aliases ("small" and "original")
- result (calling `thumbnailer.get_thumbnail_name(...)`):

```
"small": "https://some.s3.amazonaws.com/user.png.100x100_q85_crop-scale_upscale.jpg", 
"original": "https://some.s3.amazonaws.com/user.png"
```
- after checking S3 i see 2 files uploaded:

```
https://some.s3.amazonaws.com/user.png.100x100_q85_crop-scale_upscale.png
https://some.s3.amazonaws.com/user.png
```
- so S3 contains thumbnail with PNG extension, but `get_thumbnail_name` returns JPG version of a name.

**Comment by BigglesZX** [comment]
I think I might be seeing something like this at the moment. The issue raised above is that the generated thumbnail name (first code block) and name given to the actual file (second code block) don't match. Right now I'm seeing a similar situation (using S3) where `FileManager.get_file`, for a `.png` source, is looking for a thumbnail file ending in `.jpg` but the thumbnails database table and S3 filesystem have a corresponding file ending in `.png`. The existence checks therefore fail and it looks like the thumbnail might be created on every request. I'm still trying to narrow down exactly what's happening.

**Comment by gourab337** [comment]
I had a similar problem, but later realised that S3 was infact uploading transparent images. The non-transparent issue was happening due to a component I was using to wrap my image (<Paper> of material UI).
