### ISSUE TITLE
Adding zoom only works in combination with crop

### ISSUE THREAD

**Issue by jrief** [SmileyChris/easy-thumbnails#353]
This is somehow confusing.
If I use 
```
    {% thumbnail image 300x200 crop=1 zoom=50 as thumb %}
    <img src="{{ thumb.url }}" />
```
thumbnailing an image with zoom works as expected, but if I remove ``crop`` or use ``crop=0``, then no thumbnail is generated.

From reading the docs, it doesn't seem as if ``crop=1`` is mandatory whenever ``zoom`` is set - or did I miss something?

**Comment by jrief** [comment]
Please release 2.2.1 with that fix, so that I can install from PyPI rather than GitHub.

**Comment by SmileyChris** [comment]
Uploaded. :snail:
