### ISSUE TITLE
Thumbnail generation fails due to issue with optimize

### ISSUE THREAD

**Issue by nhinkle** [SmileyChris/easy-thumbnails#361]
I have optimization turned on for my Django site that uses easy_thumbnails. Here's the configuration in my settings file: 

```
INSTALLED_APPS = (
...
    'easy_thumbnails',
    'easy_thumbnails.optimize',
...
)

THUMBNAIL_DEBUG = False

THUMBNAIL_ALIASES = {
    '': {
        'avatar': {'size': (50, 50), 'crop': True, 'quality': 75},
        'detailcoverimage': {'size': (960,720), 'crop': False, 'quality': 90},
        (etc)...
     },
}

# Thumbnail optimizer
THUMBNAIL_OPTIMIZE_COMMAND = {
    'png': os.path.expanduser("~") + '/bin/optipng {filename}',
    # 'gif': '/usr/bin/optipng {filename}',
    'jpeg': os.path.expanduser("~") + '/bin/jpegoptim {filename}'
}
```

Until recently I had no issues with this. Recently when I go to add new files which should get thumbnails generated, it doesn't work - no thumbnail files show up in the relevant directory, and when using the `thumbnail_url` filter in a template, a blank string is returned. 

I tried generating thumbnails manually from the command line using `easy_thumbnails.files.generate_all_aliases`, and got the following message:

```
>>> easy_thumbnails.files.generate_all_aliases(image,True)
No handlers could be found for logger "easy_thumbnails.optimize"
```

The thumbnails were generated, and the `thumbnail_url` filter started working again for the specific image that I manually generated all aliases for. Uploading a new image resulted in the problem reappearing.

Disabling all optimization (by commenting out the `easy_thumbnails.optimize` app and all of the optimize command configuration) removes the problem. This works for now but I would like to have optimization enabled.

I am using the following versions of relevant apps:
- Django 1.6.10
- Pillow 2.7.0
- easy-thumbnails 2.2

**Comment by jrief** [comment]
I assume that you also tested to optimize the specific file using ``/usr/bin/optipng``. Just in case the file contains some weird stuff, optipng doesn't like. You have to take the file generated by Pillow, not the original file.

**Comment by nhinkle** [comment]
The error occurs with any file I upload, but I haven't tested with a file output from Pillow. I'll test that tomorrow. I've also only tested jpeg files so far, so I'll test some PNGs tomorrow as well and see if it's related to the specific optimization library.

**Comment by bmoe872** [comment]
Was there any resolution on this? I'm experiencing the same problem.

**Comment by jrief** [comment]
Without exact instructions how to reproduce this, I'm unable to work on it. Therefore I'm going to close this issue.
