### ISSUE TITLE
get or create concurrency issue

### ISSUE THREAD

**Issue by titusnicolae** [SmileyChris/easy-thumbnails#363]
https://github.com/SmileyChris/easy-thumbnails/blob/master/easy_thumbnails/models.py#L20
I've got IntegrityError: (1062, "Duplicate entry '<<somestuff>>' for key '<<otherstuff>>'")
Probably because two processes verify simultaneously that the thumbnail doesn't exist and then proceed to both create thumbnails.

**Comment by samuelcolvin** [comment]
:+1: having the same (or similar) problem. 

Error is occurring on [line 31 of models.py](https://github.com/SmileyChris/easy-thumbnails/blob/2.2/easy_thumbnails/models.py#L31) after calling `generate_all_aliases` on our worker.

which throws
```
duplicate key value violates unique constraint "easy_thumbnails_thumbnail_storage_hash_156d0c556687867a_uniq"
DETAIL:  Key (storage_hash, name, source_id)=(63c77af23a93fcbac67418e6938048ca, xxx/photos/0a53044c-357e-40d5-8372-69bdcc2d803b.JPG.200x200_q85_crop.jpg, 65470) already exists.
```

I can see we've checked if the object exists just a few lines before, could this be a problem with `storage.exists(name)` being slow? If so could we call it before the whole `try:...except:...` block?

**Comment by SmileyChris** [comment]
Hopefully that'll fix your issue @samuelcolvin but I think that's a different case than what @titusnicolae is referring to.

**Comment by SmileyChris** [comment]
#389 might have also helped fix this
