### ISSUE TITLE
Generation thumb after second hit

### ISSUE THREAD

**Issue by temi4** [SmileyChris/easy-thumbnails#365]
Hello.

I gen thumbnail
```
THUMBNAIL_ALIASES = {
    'catalog.Photo.img': {
        'list': {'size': (230, 287), 'crop': False},
        'open': {'size': (350, 700), 'crop': False},
    },
}
prod.photo.img = http://files.stylebrand.ru/media/catalog/photo/2014/10/24/09/09/53b2c01caf18c2213f33566b.jpg

<img class="img-responsive" src="{% thumbnail prod.photo.img 'open' %}"/>
```
after first hit thumbnail don't return correct
http://c2n.me/3fHuW5o
after second and next hit all good
http://c2n.me/3fHv4hp

How I may resolve this problem?

**Comment by ssbb** [comment]
Looks like you not migrated database. Try `python manage.py migrate`

**Comment by SmileyChris** [comment]
The screenshots are now 404ing, so there's not much detail provided here. Did the migration work? I'll close for now until more info is provided
