### ISSUE TITLE
Possible to use alias name in custom namer?

### ISSUE THREAD

**Issue by jaddison** [SmileyChris/easy-thumbnails#375]
Unless I'm mistaken, you're currently unable to use an alias' name in the generated thumb's filename - it was suggested in https://github.com/SmileyChris/easy-thumbnails/issues/204, but as far as I can tell, the custom namer functionality doesn't support this, as the alias name doesn't get passed in as an option into the namer at https://github.com/SmileyChris/easy-thumbnails/blob/714aa5f36894797ca6c980c9bc8cfa52a46156c1/easy_thumbnails/files.py#L444.

I would think that if the key of the aliases dictionary was added into the options before calling `get_thumbnail` at https://github.com/SmileyChris/easy-thumbnails/blob/714aa5f36894797ca6c980c9bc8cfa52a46156c1/easy_thumbnails/files.py#L91, it would be available for a custom namer then?

Edit: the reason I'm looking for this is to simplify a Rails to Django project rewrite; the legacy Rails app uses 'paperclip', which in turn uses the alias name in its thumbnail filename generation. To make this seamless (I hope), this change would be handy.

**Comment by SmileyChris** [comment]
That's a fine idea there. I might get a chance next week, but if you want to have a crack at a pull request then fire away.

Let's call the option `ALIAS` (uppercase options don't get put in prepared_options, which is a good thing)

**Comment by jaddison** [comment]
As an aside: I was looking through the list of issues/pull requests - if needed, I don't mind trying to lend a hand to integrate/respond. Your call, but with a little write access, I can try to help out.
