### ISSUE TITLE
Question: replace_alpha not used?

### ISSUE THREAD

**Issue by jaddison** [SmileyChris/easy-thumbnails#378]
The `replace_alpha` parameter isn't used here: https://github.com/SmileyChris/easy-thumbnails/blob/master/easy_thumbnails/processors.py#L299 - it looks like maybe it's supposed to be usd here: https://github.com/SmileyChris/easy-thumbnails/blob/master/easy_thumbnails/processors.py#L319

Just something I noticed, but maybe it's nothing.

**Comment by SmileyChris** [comment]
Like you noticed, it's passed to the `colorspace` function which uses it just fine.

**Comment by jaddison** [comment]
Sorry? I'm confused - the incoming parameter `replace_alpha` from https://github.com/SmileyChris/easy-thumbnails/blob/master/easy_thumbnails/processors.py#L299 is not passed into the `colorspace` function here https://github.com/SmileyChris/easy-thumbnails/blob/master/easy_thumbnails/processors.py#L319... the `background` parameter is used instead. Perhaps this is by design, but I just thought I'd mention that **the `replace_alpha incoming parameter is unused**.

Have I forgotten my Python syntax? :)

**Comment by SmileyChris** [comment]
No, you are correct. It's probably a vestigial parameter. The only reason I can see it would be there for is that the valid options list is generated from the kwargs of each processor, but can't think of why that would be an issue since it's defined explicitly in colorspace still.

**Comment by jaddison** [comment]
I absolutely thought that the incoming `replace_alpha` parameter was supposed to be used in the `colorspace()` function - after your comments and digging in a bit more, I realise my mistake.

Regardless, I created a pull request at #381 to remove the unused parameters... :)
