### ISSUE TITLE
Incorrect extension passed to custom namer

### ISSUE THREAD

**Issue by jkblgithub** [SmileyChris/easy-thumbnails#382]
I use a custom namer for my thumbnails. In Settings.py
`THUMBNAIL_NAMER = 'pony.utils.thumbnail_namer'`

Renamer code:
```
import os

def thumbnail_namer(thumbnailer, prepared_options, source_filename, thumbnail_extension, **kwargs):
    # I get fileExtension here as the one that is passed above "thumbnail_extension" is not always correct
    fileName, fileExtension = os.path.splitext(source_filename)
    new_name = source_filename
    suffix = '_medium' +fileExtension;
    new_name = new_name.replace((fileExtension), suffix)
    return new_name
```

I only have 1 thumbnail_alias defined, but have noticed the following:
1. The thumbnail_namer method gets called 3 times per image uploaded - is this expected behavior?
2. The thumbnail_extension passed in is sometimes wrong, reporting jpg when it is a png and resulting in the thumbnail not being generated. I have taken to extracting the file extension myself as a workaround - this seems to be a bug.

**Comment by SmileyChris** [comment]
Yes, it's expected that the method gets called, and that it gets called with both `png` and `jpg` extensions. Some thumbnail filters remove the transparency layer, therefore a thumb of a source png may end up being either jpg or png so we check for both.
