### ISSUE TITLE
THUMBNAIL_CACHE_DIMENSIONS generates invalid query in Django 1.8

### ISSUE THREAD

**Issue by Bartvds** [SmileyChris/easy-thumbnails#383]
We updated a project to Django 1.8; if we have THUMBNAIL_CACHE_DIMENSIONS enabled we get an error:

    Invalid field name(s) given in select_related: 'dimensions'. Choices are: (none)

This is probably because Django 1.8 validates the fields passed to select_related:

https://docs.djangoproject.com/en/1.8/releases/1.8/#select-related-now-checks-given-fields

**Comment by domenkozar** [comment]
Does https://github.com/SmileyChris/easy-thumbnails/pull/369 fix it for you (now in master)?

**Comment by SmileyChris** [comment]
Yeah, this is that issue again... new release coming very soon!
