### ISSUE TITLE
Concurrency issue in database_get_image_dimensions

### ISSUE THREAD

**Issue by jbub** [SmileyChris/easy-thumbnails#389]
Hello, i am hitting concurrency issue in `database_get_image_dimensions`:

https://github.com/SmileyChris/easy-thumbnails/blob/master/easy_thumbnails/files.py#L121-L124

When two requests are running this code and thumbnail dimension record is not present in database yet, first request will save it to the db and the second one will also try to save it (and will fail with integrity error).

```
duplicate key value violates unique constraint "easy_thumbnails_thumbnaildimensions_thumbnail_id_key"
DETAIL:  Key (thumbnail_id)=(73165) already exists.
```
We should probably try to use `get_or_create`.

**Comment by SmileyChris** [comment]
Throw me a quick pull request to merge before the imminent release, if you can spare the time!
