### ISSUE TITLE
Image dimensions strange when using image with EXIF orientation

### ISSUE THREAD

**Issue by lcaldwell** [SmileyChris/easy-thumbnails#413]
I am testing my site using easy_thumbnails when using images which have some EXIF orientation (!=1).

I have this file initially saved in a standard django image field (`Image.image_field`):
![example_exif_6_image_v1lafnm](https://cloud.githubusercontent.com/assets/8556593/15607266/7d0de386-2409-11e6-8351-12ce5d7998b4.jpg)

It has EXIF orientation 6!

I then write the following:
`from easy_thumbnails.files import get_thumbnailer
f = image_instance.image_field
thumb = get_thumbnailer(f)
thumb.get_thumbnail({'size': (300, 300)})`

The outputted image looks like this:
![example_exif_6_image_v1lafnm jpg 300x300_q85](https://cloud.githubusercontent.com/assets/8556593/15607342/f5742c68-2409-11e6-9e01-46127af83932.jpg)

Is this the intended behaviour? Am I doing something wrong? I would expect to either have ignored the EXIF data entirely and kept the image on its side or to have rotated it. What seems to have happened is that the image is rotated and then sliced bits off the side and fleshed out with black areas top and bottom so that it matches the unrotated image's aspect ratio.

**Comment by lcaldwell** [comment]
Just been looking around and realise that there is a pull request to fix this #394 ! Would be great if you could merge.

**Comment by SmileyChris** [comment]
#394 is merged, will roll a release soon

**Comment by AduchiMergen** [comment]
please release this fix soon

**Comment by StephenChan** [comment]
Glad to see this was identified and fixed, but I'd also like to see it released at some point.
