### ISSUE TITLE
Nothing working - HALP

### ISSUE THREAD

**Issue by eronaeon** [SmileyChris/easy-thumbnails#421]
Sorry for the inconvenient title. But I tried to get it working but nothing shows up! I fear this might be because I use Archlinux with Django 1.9 which might cause a mess of incompatibility of libraries with each other but I can't be sure of that!
when I try `<img src="{{ ctx.image|thumbnail_url:'avatar' }}" alt="blabla">` nothing shows up. When I make it `<img src="{{ ctx.image }}" alt="blabla">`, the original pic shows up normally. I added `THUMBNAIL_DEBUG = True` but nothing shows up in the terminal too! The load thumbnail tag is added and everything is okay but I can't see anything!

**Comment by bartmika** [comment]
I have the same problem...

+1

**Comment by hylje** [comment]
If you have Django's template debug enabled (the default), exceptions will be swallowed by django templates.

**Comment by SmileyChris** [comment]
This is hard to debug a year later... In general this is when I'd try creating the thumb in shell and see what errors are raised then
