### ISSUE TITLE
Small Images Not Crop Properly

### ISSUE THREAD

**Issue by realsby** [SmileyChris/easy-thumbnails#422]
My file sizes are 788x442 pixels. (https://mediaelire.s3.amazonaws.com/media/2016/08/1471304933968.JPG)

When I am using {% thumbnail model.image 100x100 crop %} it returns 100x100 pixels. Perfect square..
(https://mediaelire.s3.amazonaws.com/thumb/2016/08/1471304933968.JPG.100x100_q85_crop.jpg)

But when I am using {% thumbnail model.image 728x728 crop %} it returns 728x442 pixels. Not square! Its like upscale.
(https://mediaelire.s3.amazonaws.com/thumb/2016/08/1471304933968.JPG.728x728_q85_crop.jpg)

 I was expecting to see like 100x100 but more detialed. Is there any way to get what I want?

**Comment by lucasmoeskops** [comment]
`{% thumbnail model.image 728x728 crop upscale %} `is what you want maybe?

**Comment by realsby** [comment]
Yes. I realize this about 1.5 years ago. Sorry about that.
