### ISSUE TITLE
1.10 compatibility: thumbnail_cleanup command uses old BaseCommand.option_list

### ISSUE THREAD

**Issue by tonimichel** [SmileyChris/easy-thumbnails#427]
The Management Command uses the old  BaseCommand.option_list in `easy_thumbnails/management/commands/thumbnail_cleanup.py Line 124` which causes the thumbnail_cleanup command to fail on django 1.10.

Use https://docs.djangoproject.com/en/1.10/howto/custom-management-commands/#accepting-optional-arguments instead.

As a workaround you may uninstall django 1.10, reinstall django 1.9, run the command and than reinstall django 1.10 again :)

**Comment by chriscohoat** [comment]
The library django-ses solves this compatibility issue here:

https://github.com/django-ses/django-ses/blob/master/django_ses/management/commands/ses_email_address.py#L45

I'd be happy to port a similar check to easy-thumbnails if desired.
