### ISSUE TITLE
`False` conditional check?

### ISSUE THREAD

**Issue by jaddison** [SmileyChris/easy-thumbnails#431]
On line https://github.com/SmileyChris/easy-thumbnails/blob/master/easy_thumbnails/processors.py#L106, there's a check that will never pass:

```
if utils.is_transparent(im) and False:
```

I'm trying to decide is someone was debugging/testing a code path and forgot to remove it, or if it's just a bug - but if the code is valuable, it should probably be fixed?

**Comment by SmileyChris** [comment]
Impressive spotting of a 3 year old debug bug :1st_place_medal:
