### ISSUE TITLE
Add `easy_thumbnails_tags` templatetag library that mirrors traditional `thumbnail`

### ISSUE THREAD

**Issue by barseghyanartur** [SmileyChris/easy-thumbnails#435]
Add `easy_thumbnails_tags` templatetag library that mirrors traditional thumbnail.

This allows usage of `easy-thumbnails` in templates by {% load easy_thumbnails_tags %} instead of traditional {% load thumbnail %}. It's specifically useful in projects that do make use of multiple thumbnailer libraries (for instance easy-thumbnails alongside sorl-thumbnail).

Works fine in my [fork](https://github.com/barseghyanartur/easy-thumbnails/blob/master/easy_thumbnails/templatetags/easy_thumbnails_tags.py). If you, in principle, have nothing against addition of `easy_thumbnails_tags` mirror, I'll add tests and update the documentation prior making a pull request.

**Comment by SmileyChris** [comment]
Sounds fine to me!

**Comment by barseghyanartur** [comment]
Pull request is pending. I'm closing this.
