### ISSUE TITLE
Pillow dropped Py26 support

### ISSUE THREAD

**Issue by tisdall** [SmileyChris/easy-thumbnails#443]
The test for Django 1.4 makes use of the latest Pillow which doesn't support Python 2.6 and then fails.  I think it can be specified in the tox.ini to import "pillow<4.0.0".

However, pip is going to be dropping 2.6 support so maybe this project should drop support for 2.6 and just change the test to use 2.7.

Discussion on Pillow dropping 2.6 support here:  https://github.com/python-pillow/Pillow/pull/2192

**Comment by SmileyChris** [comment]
Thanks for the heads up. Probably should think about dropping old-lts support, but for now we'll just put in a conditional requirement
