### ISSUE TITLE
file.name is sth like "C:/foo/bar.jpg"

### ISSUE THREAD

**Issue by zzm88** [SmileyChris/easy-thumbnails#447]
<img src="{{ t.picture.file |thumbnail_url:'avatar' }}" alt="" />

t.picture.file is ThumbnailerImageField . But t.picture.file.name is sth like "C:/foo/bar.jpg" and the django tag returns a wrong address containing local address " C:/....."

how to return directly "bar.jpg"?

**Comment by SmileyChris** [comment]
`os.path.basename(t.picture.file.name)`
