### ISSUE TITLE
Please release 2.4 on PyPi

### ISSUE THREAD

**Issue by claudep** [SmileyChris/easy-thumbnails#452]
Several improvements have been made on master for recent Django versions. Last release is from December 2015, a new release would be nice!

**Comment by SmileyChris** [comment]
You're right, a release is well overdue. Let's get some more maintainers
for the project who can handle preparing a release and triaging incoming
issues.

My focus on the thumbnails area has moved on to easy-images. I'd like to
put some more work in to making an easy migration path to that and
deprecating this project or handing it off entirely at least.

**Comment by zw3n** [comment]
Django 1.11 will be released around [April 4](https://www.djangoproject.com/weblog/2017/mar/21/django-111-rc-1-released/) and requires the fixes made in a4467ee to run since the django.conf.BaseSettings is removed. A new release is needed to keep this handy project running.

**Comment by jungornti** [comment]
Django 1.11 is released and for now easy-thumbnail is an upgrade blocker.

**Comment by SmileyChris** [comment]
Released

**Comment by claudep** [comment]
Thanks Chris!
