### ISSUE TITLE
RuntimeError: Model class easy_thumbnails.models.Source doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

### ISSUE THREAD

**Issue by ursomniac** [SmileyChris/easy-thumbnails#463]
Looks like it's not (no longer) Django 1.10 or 1.11 compatible...?

**Comment by claudep** [comment]
I'm using it with Django 1.11. You should have issues with your INSTALLED_APPS.

**Comment by SmileyChris** [comment]
Need some more details. It's working for most like this. I'm guessing that easy_thumbnails just wasn't in INSTALLED_APPS

**Comment by Rafalonso** [comment]
I'm having the exact same problem when I upgraded from Django 1.8 to Django 1.11
