### ISSUE TITLE
Is there a way of doing a stretch resize on the image? 

### ISSUE THREAD

**Issue by aqt01** [SmileyChris/easy-thumbnails#464]
Hello!

I've using easy_thumbnail for a while and reviewed the documentation, but still cannot find a way of resizing the image **without cropping it**. I want to achieve a resize of images even if they looks stretched 
Sometimes after the resize of the picture it only fits one dimension.  For ex. if i want a image of (619,372). It  returns  (619,310) or (710,372). 

Right now i'm using this code:

> get_thumbnailer(self.img).get_thumbnail(THUMBNAIL_ALIASES['tablet_featured'])

And below my   THUMBNAIL_ALIASES:

> THUMBNAIL_ALIASES = { 
> 'target': {
>     'tablet_featured': {'size': (619, 372), 'crop': False },   
>     'mobile_featured': {'size': (320, 336), 'crop': False },
> }
> 
Any idea of how i can achieve this?

**Comment by aqt01** [comment]
I did it adding the option 'upscaling' on 'crop' like this:

> 'tablet_featured': {'size': (619, 372), 'crop': 'upscaling' },

**Comment by SmileyChris** [comment]
No, you can't unproportionally stretch the image.

Try fitting the image to the dimensions and do your own forced stretch with css.
