### ISSUE TITLE
crop = smart in template tag not work

### ISSUE THREAD

**Issue by realsby** [SmileyChris/easy-thumbnails#466]
Ty for the bad documentation. I belive it doesnt have enough samples.

I just want to crop a small image to exact size of i provide. I tried crop without smart, it cropped but output file is not exact sizes of i desired. If i upload big files its ok.

For example orginal file size is 50px to 150x .. and I want it 60px to 60px square.. I manage to get 50px to 50px but not 60px to 60px.  How can I manage that?

{% thumbnail project.image 464x752 crop=smart quality=80 as image %}

**Comment by jrief** [comment]
You have to use the ``upscale`` option as [documented here](https://easy-thumbnails.readthedocs.io/en/2.1/usage/?highlight=upscale).

So please read the docs before blaming others!

**Comment by realsby** [comment]
@jrief  
I read too much and I can tell you, upscale != crop(smart)..

When I use smaller images then 1163x527 as slide.main_image it returns not exact size I requested not upscale or crop make difference..
 
`<img width="1163" height="527" src="{% thumbnail slide.main_image 1163x527 upscale detail quality=80 %}" class="attachment-arkon_slider wp-post-image" />
`
or 

`<img width="1163" height="527" src="{% thumbnail slide.main_image 1163x527 upscale detail quality=80 %}" class="attachment-arkon_slider wp-post-image" />
`

**Comment by realsby** [comment]
Today I tried use togather upscale and crop. And it works. 
`<img width="1163" height="527" src="{% thumbnail slide.main_image 1163x527 upscale crop detail quality=80 %}"/>`

I still wonder how to use crop=<smart|scale|W,H> in template tag.

**Comment by SmileyChris** [comment]
You're right -- the docs should probably have some more examples like that. As to how to use those in a template tag, just like that! {% thumbnail img size crop=smart %}
