### ISSUE TITLE
IOError exception raised when setting THUMBNAIL_TRANSPARENCY_EXTENSION = 'jpg'

### ISSUE THREAD

**Issue by changbindu** [SmileyChris/easy-thumbnails#471]
Before Pillow 4.2.0, attempting to save an RGBA image as JPEG would discard the alpha channel. From Pillow 3.4.0, a deprecation warning was shown. **From Pillow 4.2.0, the deprecation warning is removed and an :py:exc:`IOError` is raised.**

https://github.com/python-pillow/Pillow/issues/2609
https://github.com/python-pillow/Pillow/blob/master/docs/releasenotes/4.2.0.rst#id14

**Comment by jrief** [comment]
can you provide some instructions on how to reproduce it with easy-thumbnails?

**Comment by SmileyChris** [comment]
@jrief -- if the source image has transparency, it'll be converted to 'RGBA' by the standard `colorspace` processor. Then when the engine saves it as JPEG, it'll raise this deprecation warning.
