### ISSUE TITLE
THUMBNAIL_HIGH_RESOLUTION retina @2x

### ISSUE THREAD

**Issue by toptalo** [SmileyChris/easy-thumbnails#493]
## Need to access retina image url

Template:
```html
{% load thumbnail %}
<img src="{{ profile.photo|thumbnail_url:'avatar' }}" srcset="{{ profile.photo|thumbnail_url_2x:'avatar' }} 2x" alt="" />
```

Python:

```python
from easy_thumbnails.files import get_thumbnailer
thumb_url = get_thumbnailer(profile.photo)['avatar'].url_2x
```

## Why?

Because the javascript solution has a side effect: browser begin download 1x image before javascript initialized

**Comment by jrief** [comment]
This directive has been added at a time, when browser did not support `srcset` using a workaround in Javascript, for instance [retina.js](http://imulus.github.io/retinajs/).

For modern browsers you should not use that method anymore. Instead, create two thumbnails in you template and use one for high resolution, and the other for standard resolution images.

**Comment by toptalo** [comment]
But we already have @2x image out of the box I think it will be better to just add opportunity to get it

Maybe I may make PR?

**Comment by jrief** [comment]
If you make a pull request, then please remove the whole `THUMBNAIL_HIGH_RESOLUTION ` stuff.  It's obsolete and deprecated, since we have polyfills for `srcset` and generally a good browser support: https://caniuse.com/#search=srcset

**Comment by toptalo** [comment]
Okay
