### ISSUE TITLE
easy-thunmnails don't work in production environment.

### ISSUE THREAD

**Issue by jekoie** [SmileyChris/easy-thumbnails#503]
i had install easy-thunmnails, it work fine in django set DEBUG = True  , but when set DEBUG = False
it can't load image any more.

**Comment by jekoie** [comment]
Failed to load resource: the server rabbit.png.30x30_q85_crop-smart.png:1 Failed to load resource: the server responded with a status of 404 (Not Found), but set debug=True, it work fine

**Comment by Eraldo** [comment]
I am also having issues with production code (using s3).

**Comment by lucasmoeskops** [comment]
Might be because your media files are not served from Django if Debug=False. If you haven't specified a handler for them, you will get a 404. For Amazon I don't know.

**Comment by jekoie** [comment]
yes, the server need to some settings to serve media file and the image will be showen ok.

**Comment by Eraldo** [comment]
Nope, my media files are served!
However the thumbnails are never created. I checked on s3 directly.
