### ISSUE TITLE
Generation of thumbnails of model fields without actual model fields? 

### ISSUE THREAD

**Issue by noodlebreak** [SmileyChris/easy-thumbnails#509]
Hi,

I need to know if the following is possible (as I think otherwise, after having gone through the documentation):

There are image fields in my model. What I simply want, that whenever an image is uploaded to them, their thumbnails be generated also but not requiring their own field in the database.

URL paths of the image field and the thumbnail to be like this:

*image1*: `/questions/43/internal/image1_whatevertheoriginalimagenamewas.jpg`
*thumb*: `/questions/internal/thumbs/43/image1_whatevertheoriginalimagenamewas.jpg`

*image2*: `/questions/43/internal/image2_whatevertheoriginalimagenamewas.jpg`
*thumb*: `/questions/internal/thumbs/43/image2_whatevertheoriginalimagenamewas.jpg`

And so on.

**Comment by jrief** [comment]
If you thumbnail an image using the templatetag as provided, you don't need any additional database field.
This question is too generic to be answered anyway, therefor I close it.
