### ISSUE TITLE
thumbnail_cleanup on aws s3

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [SmileyChris/easy-thumbnails#516]
Hello
Is it possible to use thumbnail_cleanup commant if i store by thimbnails on AWS s3 and if so then how?
Thx

**Comment by PetrDlouhy** [comment]
I just realised, that I was every time I ran `thumbnail_cleanup` I just deleted all my thumbnail database references with need to recreate those all my thumbnails.

The `thumbnail_cleanup` procedure is written without having storages in mind at all. It doesn't count with S3 nor having different source and thumbnail storage.

Additionally, when I tried to fix it, I didn't find any way to access the source storage (it is stored only as hash), so I am not sure if it is even possible with current DB model.
