### ISSUE TITLE
Routing to a different database

### ISSUE THREAD

**Issue by EralpB** [SmileyChris/easy-thumbnails#522]
Hello we have a readonly replica and I want to route read operations to this DB, can't find a way, is it possible without monkey-patching?

`SELECT easy_thumbnails_source . id, easy_thumbnails_source . storage_hash, easy_thumbnails_source . name, easy_thumbnails_source . modified FROM easy_thumbnails_source WHERE ( easy_thumbnails_source . name = ? AND easy_thumbnails_source . storage_hash = ? )`

I want to route this query with Thumbnail.objects.using(settings.READONLY_DATABASE).. to give the general idea.

**Comment by jrief** [comment]
You have to do that on the database itself. Read here: https://docs.djangoproject.com/en/3.0/topics/db/multi-db/#database-routers
