### ISSUE TITLE
Have easy-thumbnails regenerate thumbnail if source image is changed

### ISSUE THREAD

**Issue by robd003** [SmileyChris/easy-thumbnails#525]
It would be really helpful to have easy-thumbnails automatically regenerate the thumbnail when any kind of save action occurs on the ImageField. I've had issues where it still serves the old thumbnail after the source image has been changed.

**Comment by jrief** [comment]
easy-thumbnails does not manage your images, other applications do that. Whenever you change such an image, simply delete all of your thumbnails.
