### ISSUE TITLE
is there a way to disable thumbnail generation?

### ISSUE THREAD

**Issue by juancrescente** [SmileyChris/easy-thumbnails#526]
I'm using photos from a remote server by setting:

MEDIA_URL=http://mywebsite.com/media/

all works gine except when using thmbnails. Since it wants to get the image but it is not existent in the local env. 

How can I disable thumbails generation in my local dev env without changing the templates?

What I want is when I write this:

article.image|thumbnail_url:'crop_300_150'

I want the thumbnail_url to default to the original image URL, just for dev purposes

**Comment by fdemmer** [comment]
*is* there a way to disable thumbnail generation?
