### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by jmsmkn** [SmileyChris/easy-thumbnails#530]
Thank you for the excellent work on this project, it's a package that I use in another open source project with many happy users. 

I was wondering about the status of this project, there hasn't been a commit to master for 6 months and the current version does not work with Django 3.0 which is going to be released today. There is a PR which is waiting to add compatibility (#524) but it doesn't look like it has been reviewed. 

Is there anything that we can do to help? If the maintainers no longer have the time to do this (totally understandable!), maybe it could be moved to an organisation to support this project support this such as JazzBand? Thanks again :-)

**Comment by jrief** [comment]
Version 2.7 has been released 2 days ago. I'm currently maintaining that package.
