### ISSUE TITLE
alias namer not working

### ISSUE THREAD

**Issue by Takiro** [SmileyChris/easy-thumbnails#543]
The alias namer is not working as expected. The alias is always missing. I found the issue in the namer module. the alias function checks the `thumbnail_options` dict for a key named ALIAS, however thumbnail_options does never contain the alias name.

    def alias(thumbnailer, thumbnail_options, source_filename,
            thumbnail_extension, **kwargs):
        return '.'.join([source_filename, thumbnail_options.get('ALIAS', ''), thumbnail_extension])

**Comment by rbbonfim** [comment]
@Takiro  did you find the problem?

**Comment by Takiro** [comment]
Yes, I just opened a pull request with a fix #544
