### ISSUE TITLE
Setting to Only Generate Retina 2x Images?

### ISSUE THREAD

**Issue by samdale67** [SmileyChris/easy-thumbnails#546]
Hi all from Texas. Beautiful work on this project. Today I got easy-thumbnails up and running with no issues. However, I'm wondering if there is a way to have easy-thumbnails ONLY generate 2x/hi rez images, and reference those in a template.

Thanks,

Samuel Duncan | Head of the Research Library
Amon Carter Museum of American Art
3501 Camp Bowie Blvd., Fort Worth, TX 76107
samd@cartermuseum.org | 817.989.5042
cartermuseum.org

**Comment by samdale67** [comment]
Was able to use this solution, but maybe there's a more elegant solution in the works?

https://github.com/SmileyChris/easy-thumbnails/issues/542

**Comment by jrief** [comment]
> Was able to use this solution, but maybe there's a more elegant solution in the works?

None of which I know.

**Comment by Mogost** [comment]
A more elegant way would be to write your own template tag.
But I don't have an exact recipe for this. This is just the direction in which you can look.
