### ISSUE TITLE
Django version compatibility (especially Django 3.2)

### ISSUE THREAD

**Issue by petrklus** [SmileyChris/easy-thumbnails#574]
Hi, what are the Django versions supported? Especially curious about 3.2.

I have upgraded a fairly simple project to Django 3.2 and I while I am not getting any errors, I am not getting any images either. Any tips what may be happening?

**Comment by jrief** [comment]
I haven't had any time yet to test with Django-3.2. Sorry!

**Comment by petrklus** [comment]
> I haven't had any time yet to test with Django-3.2. Sorry!

Anything I can do to help? Happy to run the test suite and report back if slightly instructed how to do so :)

**Comment by jrief** [comment]
One thing to do is to migrate the test-suite from Travis-CI to GitHub actions, because Travis-CI will be shut down sooner or later.
If you can extract the essential parts from the current tests and migrate them, that would be really helpful.
Here is a blueprint from one of my newer projects: https://github.com/jrief/django-formset/blob/main/.github/workflows/pythonpackage.yml

**Comment by jaap3** [comment]
Just opened a PR to switch to GH Actions (#578), I'll update my other PR that adds Django 3.2 support (#573) once the switch to GH Actions has completed.

**Comment by jaap3** [comment]
I believe the recent release is now compatible with Django 3.2

**Comment by claudep** [comment]
@jrief, I guess this ticket could be closed. By the way, I would appreciate a release allowing Django 4.0. Regarding, the Django upper limit in requirements, I think that either the project is reactive enough to up the limit and release soon after a Django release, or else simply drop that upper limit.

**Comment by SmileyChris** [comment]
Closing this, and the just released v2.8.1 has Django 4 support. I also entirely removed the django upper limit restriction so it won't break as soon as 4.1 is out 😛 .

**Comment by claudep** [comment]
Thanks a lot, @SmileyChris !
