### ISSUE TITLE
Allow greater control over save_pil_image options

### ISSUE THREAD

**Issue by DrMeers** [SmileyChris/easy-thumbnails#583]
e.g. when generating a `.webp` thumbnail, I'd like to pass [`method=6`](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#webp) to `Image.save` via `save_pil_image`'s `**options`, however `engine` only passes a few (other) specific parameters. 

Currently this means saving `webp` thumbnails (which I'm doing via a custom `namer` which checks if the alias contained `webp` and passes that as the `extension`, btw, a bit of a hack...) generate images about 4x larger file size than the (slower-but-better) `method=6` equivalents.

I can't see any way to fix this apart from forking and modifying the codebase, or am I missing something?

**Comment by DrMeers** [comment]
Happy to create a PR for this.

We could:
- add a `WEBP_METHOD` setting that gets used in `save_pil_image` if `format == `WEBP`
- modify `generate_thumbnail` to take additional parameters, or look within `thumbnail_options` for extra `save_pil_image` options
- something else?

It might be worth adding a cleaner way of forcing which format you want to save the thumbnail in rather than my `namer` hack described above too.

**Comment by DrMeers** [comment]
@SmileyChris am I missing anything with respect to there being no way to set which format the thumbnails should be saved in except for hacking the `namer`?

Also any feedback/preference on the PR options above?

**Comment by SmileyChris** [comment]
Released in v2.8.1
