### ISSUE TITLE
django-filer 2.1.2, easy-thumbnails 2.8.1 and AWS

### ISSUE THREAD

**Issue by pdbethke** [SmileyChris/easy-thumbnails#587]
I've been trying to take advantage of the new svg thumbnail support and I'm running into a wall with AWS S3 - I've narrowed the issue to easy-thumbnails returning 2 errors - cannot identify image file <_io.BytesIO object at 0x0000025993F4AE50> and This backend doesn't support absolute paths. These errors crop up after uploading a new svg file to Filer. In previous threads I've seen this may be related to AWS storage and the saving process. Has anyone seen this issue and have suggestions? Maybe there is a setting im missing that better works with AWS media storage. Other than svg files, the upload and thumbnail process works fine, and writes the remote file to AWS - so I don't think its an issue with permissions.

**Comment by jrief** [comment]
Can this have to do with the fact, that SVGs are in text, while pixel based images are in binary.

I don't have any S3 access, so I can't really test this.

**Comment by pdbethke** [comment]
@safaariman - thanks! Makes a lot of sense.

**Comment by SmileyChris** [comment]
New release of 2.8.1 has what I understand is the fix for this. I'll preemtively close this - reopen if theer's still an issue
