### ISSUE TITLE
No version compatible with django 4.0 och PYPI

### ISSUE THREAD

**Issue by anderspetersson** [SmileyChris/easy-thumbnails#590]
Please release easy-thumbnails 2.8.1 on PYPI.

**Comment by bixbyr** [comment]
This  is throwing a serious wrench in things. Is there any reason to think Django 4 is incompatible?

**Comment by mrkaban** [comment]
15 days have passed and the developers have not responded. It has been a long time since the alpha versions of Django 4 were released. Repository abandoned?

**Comment by licensechecker** [comment]
79 participants in this repository and no one took care of Django 4 support? Is it time for us to switch from easy-thumbnails to something else? with more active support?

**Comment by mbi** [comment]
> 79 participants in this repository and no one took care of Django 4 support? 

The current repo HEAD works fine with Django 4, it's just a matter of packaging a new version and pushing it to PyPI.

In the meantime you can add e.g. this in your `requirements.txt` instead of `easy-thumbnails`:

```
git+https://github.com/SmileyChris/easy-thumbnails.git@92060b9fd7b617cab1ac88d149dc5021d43b35c3#egg=easy-thumbnails
```

**Comment by mrkaban** [comment]
Thanks! Installed, let's check! Thank you for responding to us!

**Comment by adrenaline681** [comment]
How can I install easy-thumbnails for Django 4 using Poetry?

**Comment by brylie** [comment]
@SmileyChris, would you please publish a version to PyPI? Also, would you consider adding more maintainers to the project so we can publish package versions?

**Comment by adrenaline681** [comment]
Any updates on this?

**Comment by SmileyChris** [comment]
Working on it right now

**Comment by SmileyChris** [comment]
Done 🚀
